# Generated by Django 2.0.7 on 2018-07-17 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180717_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='prefix',
            field=models.CharField(default='', max_length=10, verbose_name='Prefix'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialty',
            field=models.CharField(default='', max_length=50, verbose_name='Speciality'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='zipcode',
            field=models.CharField(default='', max_length=20, verbose_name='Zipcode'),
        ),
    ]
