# Generated by Django 2.0.7 on 2018-07-17 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180717_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='prefix',
        ),
    ]
