# Generated by Django 2.0.7 on 2018-07-17 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_doctor_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialty',
            field=models.CharField(default='', max_length=200, verbose_name='Speciality'),
        ),
    ]
